source 'https://github.com/qinzhongzeng55/QZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QZZMainViewKit_Example' do
  pod 'QZZMainViewKit', :path => '../'
  pod 'QZZFunctionalComponentsKit'
  target 'QZZMainViewKit_Tests' do
    inherit! :search_paths

    
  end
end
